/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import static java.lang.Math.PI;
import java.lang.Math;
import static java.lang.Math.cos;
import static java.lang.Math.log;
import static java.lang.Math.log10;
import static java.lang.Math.random;
import static java.lang.Math.sin;
import static java.lang.Math.tan;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.runtime.JSType.isNumber;

/**
 *
 * @author User
 */
public class CalculateTheNumber extends javax.swing.JFrame {

    /**
     * Creates new form CalculateTheNumber
     */
    public CalculateTheNumber() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumber1 = new javax.swing.JTextField();
        txtNumber2 = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btnMul = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnPercentage = new javax.swing.JButton();
        btnPower = new javax.swing.JButton();
        btnSin = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnRemainder = new javax.swing.JButton();
        btnFactorial = new javax.swing.JButton();
        btnnCr = new javax.swing.JButton();
        btnRoot = new javax.swing.JButton();
        btnLn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 204, 255));
        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculator");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter Number 1");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter Number 2");
        jLabel3.setOpaque(true);

        txtNumber1.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        txtNumber1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumber1ActionPerformed(evt);
            }
        });

        txtNumber2.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        txtNumber2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSub.setText("-");
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });

        btnMul.setText("*");
        btnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulActionPerformed(evt);
            }
        });

        btnDiv.setText("/");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnPercentage.setText("%");
        btnPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercentageActionPerformed(evt);
            }
        });

        btnPower.setText("^");
        btnPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerActionPerformed(evt);
            }
        });

        btnSin.setText("Sin");
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });

        btnCos.setText("Cos");
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });

        btnTan.setText("Tan");
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });

        btnLog.setText("log");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        btnRemainder.setText("Remainder");
        btnRemainder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemainderActionPerformed(evt);
            }
        });

        btnFactorial.setText("!");
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });

        btnnCr.setText("nCr");
        btnnCr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnCrActionPerformed(evt);
            }
        });

        btnRoot.setText("Root");
        btnRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRootActionPerformed(evt);
            }
        });

        btnLn.setText("ln");
        btnLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(txtNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFactorial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnnCr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btnSin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemainder)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDiv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPower)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPercentage)
                        .addGap(12, 12, 12)
                        .addComponent(btnLn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRoot)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnSub)
                            .addComponent(btnFactorial)
                            .addComponent(btnnCr)
                            .addComponent(btnLog)
                            .addComponent(btnTan)
                            .addComponent(btnSin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnRemainder)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMul)
                    .addComponent(btnDiv)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPercentage)
                        .addComponent(btnRoot)
                        .addComponent(btnPower)
                        .addComponent(btnCos)
                        .addComponent(btnLn)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String inp1 = txtNumber1.getText();
        String inp2 = txtNumber2.getText();
        float input1 = Float.parseFloat(inp1);
        float input2 = Float.parseFloat(inp2);
        float add = input1+input2;
        String result=String.valueOf(add);
        JOptionPane.showMessageDialog(this,"The addition of "+input1+" and "+input2+" is = "+result,"",JOptionPane.INFORMATION_MESSAGE);
        txtNumber1.setText(result);
        txtNumber2.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
        String inp1 = txtNumber1.getText();
        String inp2 = txtNumber2.getText();
        float input1 = Float.parseFloat(inp1);
        float input2 = Float.parseFloat(inp2);
        float sub = input1-input2;
        DecimalFormat df = new DecimalFormat("#.###");
        df.setRoundingMode(RoundingMode.CEILING);
        String result=String.valueOf(df.format(sub));
        JOptionPane.showMessageDialog(this,"The Substraction of "+input1+" - "+input2+" is = "+result,"",JOptionPane.INFORMATION_MESSAGE);
        txtNumber1.setText(result);
        txtNumber2.setText("");
    }//GEN-LAST:event_btnSubActionPerformed

    private void btnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulActionPerformed
        String inp1 = txtNumber1.getText();
        String inp2 = txtNumber2.getText();
        float input1 = Float.parseFloat(inp1);
        float input2 = Float.parseFloat(inp2);
        float mul = input1*input2;
        String result=String.valueOf(mul);
        JOptionPane.showMessageDialog(this,"The Multiplexion of "+input1+" and "+input2+" is = "+result,"",JOptionPane.INFORMATION_MESSAGE);
        txtNumber1.setText(result);
        txtNumber2.setText("");
    }//GEN-LAST:event_btnMulActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        String inp1 = txtNumber1.getText();
        String inp2 = txtNumber2.getText();
        float input1 = Float.parseFloat(inp1);
        float input2 = Float.parseFloat(inp2);
        if(input2==0){
            JOptionPane.showMessageDialog(this,"!!!!  Enter Correct divisor  !!!!","",JOptionPane.ERROR_MESSAGE);
        }else{
            float div = input1/input2;
            String result=String.valueOf(div);
            JOptionPane.showMessageDialog(this,"The Divition of "+input1+" by "+input2+" is = "+result,"",JOptionPane.INFORMATION_MESSAGE);
            txtNumber1.setText(result);
            txtNumber2.setText("");
        }
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
        String inp1 = txtNumber1.getText();
        float input1 = Float.parseFloat(inp1);
        if(input1 == (int)input1){
            BigInteger fact = BigInteger.valueOf(1);
            if(input1>=0){
                for (int i = 1; i <= input1; i++)
                fact = fact.multiply(BigInteger.valueOf(i));
            }else{
               for(int i = (int) input1;i<0;i++){
                   fact = fact.multiply(BigInteger.valueOf(i));
               }
            }
            String result=String.valueOf(fact);
            JOptionPane.showMessageDialog(this,"The Factorial of "+input1+" is = "+result,"",JOptionPane.INFORMATION_MESSAGE);
            txtNumber1.setText(result);
            txtNumber2.setText("");
        }else{
            JOptionPane.showMessageDialog(this,"!!!! Enter Correct Integer Number !!!!","",JOptionPane.ERROR_MESSAGE);
            String input3=String.valueOf(input1);
            txtNumber1.setText(input3);
            txtNumber2.setText("");
        }
    }//GEN-LAST:event_btnFactorialActionPerformed

    private void btnPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerActionPerformed
        String inp1 = txtNumber1.getText();
        String inp2 = txtNumber2.getText();
        double input1 = Double.parseDouble(inp1);
        double input2 = Double.parseDouble(inp2);
        double power = Math.pow(input1, input2);
        float power1 = (float) power;
        DecimalFormat df = new DecimalFormat("#.####");
        df.setRoundingMode(RoundingMode.CEILING);
        String pow = df.format(power1);
        float pow1 = Float.parseFloat(pow);
        String result=String.valueOf(pow1);
        JOptionPane.showMessageDialog(this,"The "+input2+"th Power of " +input1+" is = "+result,"",JOptionPane.INFORMATION_MESSAGE);
        txtNumber1.setText(result);
        txtNumber2.setText("");    
    }//GEN-LAST:event_btnPowerActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        String inp1 = txtNumber1.getText();
        float input1 = Float.parseFloat(inp1);
        if(input1>0){
            double log = log10(input1);
            String result=String.valueOf(log);
            JOptionPane.showMessageDialog(this,"The Log value is = "+result,"",JOptionPane.INFORMATION_MESSAGE);
            txtNumber1.setText(result);
            txtNumber2.setText("");
        }else{
            JOptionPane.showMessageDialog(this,"!!!! Enter Correct Integer Number !!!!","",JOptionPane.ERROR_MESSAGE);
            txtNumber1.setText("");
            txtNumber2.setText("");
        }
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
        String inp1 = txtNumber1.getText();
        float input1 = Float.parseFloat(inp1);
        float sin = (float) sin((PI*input1)/180);
        String result=String.valueOf(sin);
        JOptionPane.showMessageDialog(this,"The Sin value is = "+result,"",JOptionPane.INFORMATION_MESSAGE);
        txtNumber1.setText(result);
        txtNumber2.setText("");
    }//GEN-LAST:event_btnSinActionPerformed

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        String inp1 = txtNumber1.getText();
        float input1 = Float.parseFloat(inp1);
        float cos = (float) cos((PI*input1)/180);
        String result=String.valueOf(cos);
        JOptionPane.showMessageDialog(this,"The Cos value is = "+result,"",JOptionPane.INFORMATION_MESSAGE);
        txtNumber1.setText(result);
        txtNumber2.setText("");
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        String inp1 = txtNumber1.getText();
        float input1 = Float.parseFloat(inp1);
        float tan = (float) tan((PI*input1)/180);
        String result=String.valueOf(tan);
        JOptionPane.showMessageDialog(this,"The Tan value is = "+result,"",JOptionPane.INFORMATION_MESSAGE);
        txtNumber1.setText(result);
        txtNumber2.setText("");
    }//GEN-LAST:event_btnTanActionPerformed

    private void btnRemainderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemainderActionPerformed
        String inp1 = txtNumber1.getText();
        String inp2 = txtNumber2.getText();
        float input1 = Float.parseFloat(inp1);
        float input2 = Float.parseFloat(inp2);
        float modulo = input1%input2;
        int quotient = (int)input1/(int)input2;
        String result=String.valueOf(modulo);
        JOptionPane.showMessageDialog(this,"The Remainder is = "+result+"\nThe Quotient is = "+quotient,"",JOptionPane.INFORMATION_MESSAGE);
        txtNumber1.setText(result);
        txtNumber2.setText("");
    }//GEN-LAST:event_btnRemainderActionPerformed

    private void btnPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercentageActionPerformed
        String inp1 = txtNumber1.getText();
        String inp2 = txtNumber2.getText();
        float input1 = Float.parseFloat(inp1);
        float input2 = Float.parseFloat(inp2);
        float percentage = (input1/input2)*100;
        String result=String.valueOf(percentage);
        JOptionPane.showMessageDialog(this,"The Percentage of "+input1+"/"+input2+" is = "+result+" %","",JOptionPane.INFORMATION_MESSAGE);
        txtNumber1.setText(result);
        txtNumber2.setText("");
    }//GEN-LAST:event_btnPercentageActionPerformed

    private void btnnCrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnCrActionPerformed
        String inp1 = txtNumber1.getText();
        String inp2 = txtNumber2.getText();
        float input1 = Float.parseFloat(inp1);
        float input2 = Float.parseFloat(inp2);
        if(input1>input2){
            if(input1 == (int)input1 && input2 ==(int)input2){
                BigInteger fact1 = BigInteger.valueOf(1);
                for (int i = 1; i <= input1; i++)
                    fact1 = fact1.multiply(BigInteger.valueOf(i));
                BigInteger fact2 = BigInteger.valueOf(1);
                for (int i = 1; i <= input2; i++)
                    fact2 = fact2.multiply(BigInteger.valueOf(i)); 
                int sub = (int)(input1-input2);
                BigInteger fact3 = BigInteger.valueOf(1);
                for (int i = 1; i <= sub; i++)
                    fact3 = fact3.multiply(BigInteger.valueOf(i));
                BigInteger fact4 = fact3.multiply(fact2);
                BigInteger fact5 = fact1.divide(fact4);
                String result=String.valueOf(fact5);
                JOptionPane.showMessageDialog(this,"The "+(int)input1+"C"+(int)input2+" is = "+result,"",JOptionPane.INFORMATION_MESSAGE);
                txtNumber1.setText(result);
                txtNumber2.setText("");
            }else{
                JOptionPane.showMessageDialog(this,"!!!! Enter Correct Integer Number !!!!","",JOptionPane.ERROR_MESSAGE);
                String input3=String.valueOf(input1);
                String input4=String.valueOf(input2);
                txtNumber1.setText(input3);
                txtNumber2.setText(input4);
            }
        }else{
            JOptionPane.showMessageDialog(this,"!!!! Enter Correct Number !!!!","",JOptionPane.ERROR_MESSAGE);
            String input3=String.valueOf(input1);
            String input4=String.valueOf(input2);
            txtNumber1.setText(input3);
            txtNumber2.setText(input4);
        }
    }//GEN-LAST:event_btnnCrActionPerformed

    private void btnRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRootActionPerformed
        String inp1 = txtNumber1.getText();
        String inp2 = txtNumber2.getText();
        double input1 = Double.parseDouble(inp1);
        int input2 = Integer.parseInt(inp2);
        boolean flag = true;
        if(input1>=1){
            
            for(double i=1;i<input1;i+=0.0001){
            DecimalFormat df = new DecimalFormat("#.####");
            String j = df.format(i);
           // System.out.println(j);
            float k = Float.parseFloat(j);
            //System.out.println(k);
            double pow =   Math.pow(i,input2);
            //System.out.println(pow);
            float pow1=(float) pow;
            float num = (float) input1;
            //System.out.println(pow1);
            //break;
            if(pow1==num){
                System.out.print("hii");
                DecimalFormat df1 = new DecimalFormat("#.##");
                df1.setRoundingMode(RoundingMode.CEILING);
                String pow2 = df1.format(i);
                float pow3 = Float.parseFloat(pow2);
                String result = df1.format(pow1);
                JOptionPane.showMessageDialog(this,"The "+input2+"th Root of "+input1+" is = "+j,"",JOptionPane.INFORMATION_MESSAGE);
                txtNumber1.setText("");
                txtNumber2.setText("");
                flag = false;
                break;            
            }
        
        
           /* if(pow == input1){
                String result=String.valueOf(i);
                JOptionPane.showMessageDialog(this,"The "+input2+"th Root of "+input1+" is = "+result,"",JOptionPane.INFORMATION_MESSAGE);
                txtNumber1.setText(result);
                txtNumber2.setText("");
                flag = false;
                break;
            }*/
        }
        if(flag==true){
                
                JOptionPane.showMessageDialog(this,"!!!! Root Can't be Possible !!!!","",JOptionPane.ERROR_MESSAGE);
                String input3=String.valueOf(input1);
                String input4=String.valueOf(input2);
                txtNumber1.setText(input3);
                txtNumber2.setText(input4);
        }
            
        }else{
            for(double i=0.0001;i<1;i+=0.0001){
            DecimalFormat df = new DecimalFormat("#.####");
            String j = df.format(i);
           // System.out.println(j);
            float k = Float.parseFloat(j);
            //System.out.println(k);
            double pow =   Math.pow(i,input2);
            //System.out.println(pow);
            float pow1=(float) pow;
            float num = (float) input1;
            //System.out.println(pow1);
            //break;
            if(pow1==num){
                System.out.print("hii");
                DecimalFormat df1 = new DecimalFormat("#.####");
                df1.setRoundingMode(RoundingMode.CEILING);
                String pow2 = df1.format(i);
                float pow3 = Float.parseFloat(pow2);
                String result = df1.format(pow1);
                JOptionPane.showMessageDialog(this,"The "+input2+"th Root of "+input1+" is = "+j,"",JOptionPane.INFORMATION_MESSAGE);
                txtNumber1.setText("");
                txtNumber2.setText("");
                flag = false;
                break;            
            }
        
        
           /* if(pow == input1){
                String result=String.valueOf(i);
                JOptionPane.showMessageDialog(this,"The "+input2+"th Root of "+input1+" is = "+result,"",JOptionPane.INFORMATION_MESSAGE);
                txtNumber1.setText(result);
                txtNumber2.setText("");
                flag = false;
                break;
            }*/
        }
        if(flag==true){
                
                JOptionPane.showMessageDialog(this,"!!!! Root Can't be Possible !!!!","",JOptionPane.ERROR_MESSAGE);
                String input3=String.valueOf(input1);
                String input4=String.valueOf(input2);
                txtNumber1.setText(input3);
                txtNumber2.setText(input4);
        }
        }
    }//GEN-LAST:event_btnRootActionPerformed

    private void btnLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLnActionPerformed
        String inp1 = txtNumber1.getText();
        float input1 = Float.parseFloat(inp1);
        if(input1>0){
            double log = log(input1);
            String result=String.valueOf(log);
            JOptionPane.showMessageDialog(this,"The Log value 0f "+input1+" is = "+result,"",JOptionPane.INFORMATION_MESSAGE);
            txtNumber1.setText(result);
            txtNumber2.setText("");
        }else{
            JOptionPane.showMessageDialog(this,"!!!! Enter Correct Positive Number !!!!","",JOptionPane.ERROR_MESSAGE);
            txtNumber1.setText("");
            txtNumber2.setText("");
        }
    }//GEN-LAST:event_btnLnActionPerformed

    private void txtNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumber1ActionPerformed
        
    }//GEN-LAST:event_txtNumber1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculateTheNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculateTheNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculateTheNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculateTheNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateTheNumber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnLn;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnMul;
    private javax.swing.JButton btnPercentage;
    private javax.swing.JButton btnPower;
    private javax.swing.JButton btnRemainder;
    private javax.swing.JButton btnRoot;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnSub;
    private javax.swing.JButton btnTan;
    private javax.swing.JButton btnnCr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNumber1;
    private javax.swing.JTextField txtNumber2;
    // End of variables declaration//GEN-END:variables
}